spring.application.name=API-Gateway
server.port=9000
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.urls[0].name=Setor Service
springdoc.swagger-ui.urls[0].url=/aggregate/setor-service/v3/api-docs
#springdoc.swagger-ui.urls[1].name=Triagem Service
#springdoc.swagger-ui.urls[1].url=/aggregate/triagem-service/v3/api-docs
#springdoc.swagger-ui.urls[2].name=Agendamento Service
#springdoc.swagger-ui.urls[2].url=/aggregate/agendamento-service/v3/api-docs
#springdoc.swagger-ui.urls[3].name=Atendimento Service
#springdoc.swagger-ui.urls[3].url=/aggregate/atendimento-service/v3/api-docs
#springdoc.swagger-ui.urls[4].name=CadastroCliente Service
#springdoc.swagger-ui.urls[5].url=/aggregate/cadastroCliente-service/v3/api-docs
