spring:
  application:
    name: Agendamento-Service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AgendamentoServiceDB;encrypt=true;trustServerCertificate=true
    username: agendamento_user
    password: admintcs
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8082