spring:

    application:
        name : Triagem

    datasource:
        url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Triagem;
        username: rafael
        password: 123
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect

    profiles:
        active: dev

#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka # URL do seu Eureka Server (ajuste a porta se for diferente)
#    instance:
#        preferIpAddress: true

clients:
    catalogo-service:
        url: http://localhost:9000/catalogo
    cadastro-cliente-service:
        url: http://localhost:9000/cliente

server:
    port: 8081

