server:
  port:
    8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: TarefasFuncionario-Service


  data:
    mongodb:
      uri: mongodb://localhost:27017/tarefa-service
