server:
    port: 8085


spring:
    application:
      name: DocumentacaoService
    datasource:
      url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Documentos;
      username: user
      password: admintcs
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
      hibernate:
        ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect

      profiles:
        active: dev
  

document:
    storage:
      location: ./uploads-documentos

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#triagem-service:
#  url: http://localhost:8081/
#agendamento-service:
#  url: http://localhost:8082/