spring:
  application:
    name: ClienteService

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ClienteData;encrypt=true;trustServerCertificate=true
    username: rafael
#    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true

server:
  port: 8086

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
